// MARK: Beat -
// % Swift answers

// MARK: Reference -


// MARK: Question -
//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.


import Foundation

// MARK: Answer - 1
class Solution389 {

}

// MARK: OtherSolutions - 1

